name: Sphinx Build OnPremises

on:
  push:
    branches: [ redesign-2021 ]
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'The new version number'
        required: false 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare files
      run: |
          sudo apt-get install -y rename
          cp -fr ./Common/. ./source/
          cp -fr ./OnPremises/. ./source/

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."

    - name: To lowercase
      run: |
          find ./build/html/ -depth -exec rename -n 'y/[A-Z]/[a-z]/' {} ";"

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "build/html/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /var/www/html/docs/help-desk-onpremises/v1.x/